In [1]:
## Installing the numpy library
! pip install numpy

In [2]:
## importing the library
import numpy as np

In [4]:
## 1-d array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
a.dtype ## checking the array datatype

dtype('int32')

In [6]:
a1 = np.array([1,2,3,56,78,"bc","ad"])
a1

array(['1', '2', '3', '56', '78', 'bc', 'ad'], dtype='<U11')

In [7]:
a1.dtype

dtype('<U11')

In [8]:
a = np.append(a,67) ## appending a single element into an array
a

array([ 1,  2,  3,  4,  5, 67])

In [9]:
a = np.append(a,[23,56,98])   ### appending group of elements
a

array([ 1,  2,  3,  4,  5, 67, 23, 56, 98])

In [11]:
an = np.arange(1,11,2)  ## creating array of range of elements with step value
an

array([1, 3, 5, 7, 9])

In [13]:
al = np.linspace(1,10,20) ### creating array with in the given range with required no of elements
al

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [15]:
alg = np.logspace(1,10,20)  ### creating tha array within the given range 
                           #### with  required no of elements with their log values
alg

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [17]:
np.full(10,"abc")  ## repeating required no of times and making into array

array(['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc',
       'abc'], dtype='<U3')

In [19]:
np.zeros(10,dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
### 2-d array
a2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a2.ndim
a2.size
a2.dtype
a2.itemsize
a2.shape
a2.nbytes

36

In [29]:
### 3-d array : combination of 2-d arrays
a3 = np.array([[[1,2,3,4],[4,5,6,7]],[[9,8,5,1],[3,4,7,9]]])
a3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 5, 1],
        [3, 4, 7, 9]]])

In [31]:
### multidimensional arrays
am = np.array([1,2,3,4,5],ndmin = 20)
am

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]]]]]]]]]]])

In [33]:
am.ndim

20

### Accessing the elements from the array

In [34]:
a

array([ 1,  2,  3,  4,  5, 67, 23, 56, 98])

In [37]:
len(a)

9

In [38]:
a[8]

98

In [39]:
a[-1]

98

In [40]:
a[2]

3

In [41]:
a[-5]

5

In [43]:
a[1:5]

array([2, 3, 4, 5])

In [44]:
a[5:]

array([67, 23, 56, 98])

In [46]:
a[-4:]

array([67, 23, 56, 98])

In [47]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2[0][2]

3

In [50]:
a2[0,2]  ## row index, element index

3

In [51]:
a2[:,0:1]

array([[1],
       [4],
       [7]])

In [54]:
a2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a2[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
a2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [57]:
### 3-d array
a3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 5, 1],
        [3, 4, 7, 9]]])

In [60]:
a3[0][1][2]

6

In [61]:
a3[0,1,2]

6

In [65]:
a3[1,1,-2]

7

In [67]:
a3[:,0]

array([[1, 2, 3, 4],
       [9, 8, 5, 1]])

In [68]:
a3[:,0,0:2]

array([[1, 2],
       [9, 8]])

In [70]:
a3[[0,1,1,0],[1,1,0,1]]   # a3[(0,1),(1,1)(1,0)(0,1)]  # fancy indexing

array([[4, 5, 6, 7],
       [3, 4, 7, 9],
       [9, 8, 5, 1],
       [4, 5, 6, 7]])

In [74]:
a3[0,1]

array([4, 5, 6, 7])

In [76]:
a3[[0,1,1,0],[1,1,0,1],[1,2,3,1]] ## (0,1,1)

array([5, 7, 1, 5])

In [77]:
a3[0,1,1]

5

In [78]:
a3  # 1,6,8,9

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[9, 8, 5, 1],
        [3, 4, 7, 9]]])

In [81]:
a3[[0,0,1,1],[0,1,0,1],[0,2,1,3]]

array([1, 6, 8, 9])

In [82]:
ar = np.arange(1,21)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
## 10,2 - 4,5 - 5,4- 2,10 - 2,2,5
b = ar.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [86]:
ar.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [87]:
ar.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [88]:
ar.reshape(5,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [89]:
ar.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [90]:
ar.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [91]:
ar.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [93]:
ar.reshape(2,-1,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [94]:
np.arange(31,41).reshape(-1,2)

array([[31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40]])

### Iteration of arrays

In [96]:
for i in a: 
    print(i,end = " ")

1 2 3 4 5 67 23 56 98 

In [98]:
for i in a2:  ## i holds rows
    for j in i:  ## j holds row elements
        print(j,end = " ")

1 2 3 4 5 6 7 8 9 

In [100]:
for i in a3:           ## i holds 2-d array
    for j in i:        ### j holds rows
        for k in j:    ### k holds elements
            print(k,end = " ")

1 2 3 4 4 5 6 7 9 8 5 1 3 4 7 9 

In [101]:
for i in np.nditer(a3):  ## keyword for iterating the array
    print(i,end = " ")

1 2 3 4 4 5 6 7 9 8 5 1 3 4 7 9 

In [102]:
## 1-d array
a = np.arange(1,10)
b = np.arange(11,20)
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [103]:
## 2-d array
c = a.reshape(3,3)
d = b.reshape(3,3)
np.concatenate((c,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [105]:
np.concatenate((a,c))

ValueError: all the input arrays must have same number of dimensions

### statistical and math operations

In [106]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
c.min(),c.max()

(1, 9)

In [108]:
c.argmin()

0

In [109]:
c.argmax()

8

In [110]:
c.mean()

5.0

In [113]:
np.median(c)

5.0

In [117]:
np.std(c)

2.581988897471611

In [120]:
np.var(c)

6.666666666666667

In [121]:
np.sum(c)

45

In [122]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
np.sum(c,1)  # sum of the elements of rows

array([ 6, 15, 24])

In [124]:
np.sum(c,0)  # sum of the elements of columns

array([12, 15, 18])

In [125]:
np.argmax(c,1)

array([2, 2, 2], dtype=int64)

In [126]:
np.argmin(c,0)

array([0, 0, 0], dtype=int64)

In [127]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [128]:
np.exp(c)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [129]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
org = c.copy()
org

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
k = org.ravel()
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
k = np.append(k,87)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 87])

In [135]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
r = c.ravel()
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
r[0] = 678
r

array([678,   2,   3,   4,   5,   6,   7,   8,   9])

In [138]:
c

array([[678,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [139]:
f = c.flatten()
f

array([678,   2,   3,   4,   5,   6,   7,   8,   9])

In [141]:
f[5] = 500
f

array([678,   2,   3,   4,   5, 500,   7,   8,   9])

In [142]:
c

array([[678,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [144]:
np.random.rand()

0.40341409447815757

In [146]:
np.random.randint(1,20)

4

In [147]:
np.random.randint(100,size = (20))

array([20, 45, 73, 32, 91, 29, 48, 33, 90, 11, 27, 14,  6, 71,  9, 28, 55,
       83, 15, 69])

In [148]:
np.random.randint(150,size = (2,3,4))

array([[[148, 112,  79,  18],
        [ 50, 129,  83,  72],
        [ 21,  13, 120,  75]],

       [[ 29,  57,  45,  16],
        [ 42,  94, 147,  95],
        [ 76,  11, 122,  39]]])

In [150]:
np.random.choice([13,56,78,90,2,4,3,200])

56

In [153]:
np.random.choice([13,56,78,90,2,4,3,200],size = (3,2))

array([[13, 90],
       [56,  3],
       [90,  4]])

In [154]:
c

array([[678,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [155]:
np.random.shuffle(c)

In [156]:
c

array([[678,   2,   3],
       [  7,   8,   9],
       [  4,   5,   6]])

In [157]:
np.random.randn(10)

array([-0.51436138, -1.48360501, -0.66220997,  1.1318538 ,  1.24524502,
        0.15477772,  0.19108565, -1.02703977, -1.35043592,  0.12010717])

In [158]:
np.random.normal()

1.4355273071881427

In [160]:
np.random.binomial(10,p = [0.1],size = (4))

array([0, 1, 1, 2])

In [162]:
d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [163]:
np.hstack((c,d))

array([[678,   2,   3,  11,  12,  13],
       [  7,   8,   9,  14,  15,  16],
       [  4,   5,   6,  17,  18,  19]])

In [164]:
np.vstack((c,d))

array([[678,   2,   3],
       [  7,   8,   9],
       [  4,   5,   6],
       [ 11,  12,  13],
       [ 14,  15,  16],
       [ 17,  18,  19]])

In [165]:
np.sin(c)

array([[-0.55137639,  0.90929743,  0.14112001],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [166]:
np.cos(c)

array([[ 0.8342566 , -0.41614684, -0.9899925 ],
       [ 0.75390225, -0.14550003, -0.91113026],
       [-0.65364362,  0.28366219,  0.96017029]])

In [167]:
np.tan(c)

array([[-0.66091941, -2.18503986, -0.14254654],
       [ 0.87144798, -6.79971146, -0.45231566],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [168]:
np.add(c,d)

array([[689,  14,  16],
       [ 21,  23,  25],
       [ 21,  23,  25]])

In [169]:
np.multiply(c,d)

array([[7458,   24,   39],
       [  98,  120,  144],
       [  68,   90,  114]])

In [170]:
np.divide(c,d)

array([[61.63636364,  0.16666667,  0.23076923],
       [ 0.5       ,  0.53333333,  0.5625    ],
       [ 0.23529412,  0.27777778,  0.31578947]])

In [171]:
np.mod(c,d)

array([[7, 2, 3],
       [7, 8, 9],
       [4, 5, 6]], dtype=int32)

In [172]:
np.add(c,5)

array([[683,   7,   8],
       [ 12,  13,  14],
       [  9,  10,  11]])

In [173]:
np.remainder(c,3)

array([[0, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [174]:
np.dot(c,d)

array([[7537, 8220, 8903],
       [ 342,  366,  390],
       [ 216,  231,  246]])

In [175]:
np.transpose(c)

array([[678,   7,   4],
       [  2,   8,   5],
       [  3,   9,   6]])

In [176]:
c

array([[678,   2,   3],
       [  7,   8,   9],
       [  4,   5,   6]])

In [177]:
c.T

array([[678,   7,   4],
       [  2,   8,   5],
       [  3,   9,   6]])

In [178]:
np.power(c,2)

array([[459684,      4,      9],
       [    49,     64,     81],
       [    16,     25,     36]], dtype=int32)

In [180]:
np.reciprocal(c,dtype = float)

array([[0.00147493, 0.5       , 0.33333333],
       [0.14285714, 0.125     , 0.11111111],
       [0.25      , 0.2       , 0.16666667]])

In [181]:
np.degrees(c)

array([[38846.53850987,   114.59155903,   171.88733854],
       [  401.07045659,   458.3662361 ,   515.66201562],
       [  229.18311805,   286.47889757,   343.77467708]])

In [182]:
np.diff(c)

array([[-676,    1],
       [   1,    1],
       [   1,    1]])

In [183]:
c

array([[678,   2,   3],
       [  7,   8,   9],
       [  4,   5,   6]])

In [184]:
np.ediff1d(c)

array([-676,    1,    4,    1,    1,   -5,    1,    1])

In [185]:
a = np.array([1+2j,4+7j,9+6j])
a

array([1.+2.j, 4.+7.j, 9.+6.j])

In [186]:
np.real(a)

array([1., 4., 9.])

In [187]:
np.imag(a)

array([2., 7., 6.])

In [188]:
np.log(c)

array([[6.51914729, 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458],
       [1.38629436, 1.60943791, 1.79175947]])

In [189]:
np.log2(c)

array([[9.40514146, 1.        , 1.5849625 ],
       [2.80735492, 3.        , 3.169925  ],
       [2.        , 2.32192809, 2.5849625 ]])

In [190]:
np.log10(c)

array([[2.83122969, 0.30103   , 0.47712125],
       [0.84509804, 0.90308999, 0.95424251],
       [0.60205999, 0.69897   , 0.77815125]])

In [191]:
c

array([[678,   2,   3],
       [  7,   8,   9],
       [  4,   5,   6]])

In [192]:
c.sort()

In [194]:
c.sort(axis = 0)

In [195]:
c

array([[  2,   3,   6],
       [  4,   5,   9],
       [  7,   8, 678]])

In [196]:
np.array_equal(c,d)

False

In [197]:
np.not_equal(c,d)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [198]:
np.equal(c,d)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [199]:
np.logical_or(c,d)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [200]:
np.logical_and(c,d)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [205]:
h = np.logical_not(c)
h

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [206]:
np.save("myarray",h)

In [207]:
np.load("myarray.npy")

array([[False, False, False],
       [False, False, False],
       [False, False, False]])